services:
  pythia_db:
    image: postgres:15-alpine
    container_name: pythia_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pythia_postgres_data:/var/lib/postgresql/data

volumes:
  pythia_postgres_data: