"""change interpretation to json

Revision ID: 0de3557fe29f
Revises: 348ec70bdf73
Create Date: 2026-04-14 16:04:57.260738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de3557fe29f'
down_revision: Union[str, Sequence[str], None] = '348ec70bdf73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'readings',
        'interpretation',
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        postgresql_using='interpretation::json'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'interpretation',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
