"""rename_candles_to_tokens_and_remove_last_refill

Revision ID: 9fa864160fd9
Revises: 0de3557fe29f
Create Date: 2026-06-26 18:18:28.693748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa864160fd9'
down_revision: Union[str, Sequence[str], None] = '0de3557fe29f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readings', 'interpretation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('users', sa.Column('tokens', sa.Integer(), nullable=False))
    op.drop_column('users', 'last_refill')
    op.drop_column('users', 'candles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('candles', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_refill', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'tokens')
    op.alter_column('readings', 'interpretation',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
